package com.jy.modules.drools.domain;
import com.jy.modules.drools.entity.DroolsResultDTO;
global DroolsResultDTO droolsResultDTO

import java.text.*;
import java.util.*
import com.jy.modules.drools.util.FunctionUtil;
import com.jy.modules.drools.domain.Sale;

function String formatDate(Date date) {
	SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
	return sdf.format(date);
}

function boolean canDiscount(int price, int amount, int discountBoundary) {
	if (price * amount > discountBoundary) {
		return true;
	}
	return false;
}

function String print(Sale sale) {
	Date date = FunctionUtil.plusDay(sale.getDate(), 10);
	String result = "销售单: " + sale.getSaleCode() + ", 时间：" + formatDate(date) + ", 金额：" + (sale.getAmount() * sale.getPrice());
	System.out.println(result);
	return result;
}

rule "Sale Discount"
	when 
		$s : Sale(canDiscount(price, amount, 100));
	then 
		print($s);
		droolsResultDTO.setRetStatus(true);
        droolsResultDTO.setRemark(print($s));
        droolsResultDTO.setRuleScore(120f);
end