package com.jy.modules.drools.domain;
import com.jy.modules.drools.entity.DroolsResultDTO;
global DroolsResultDTO droolsResultDTO
declare Person
	@author(Angus)
	@age(33)
	id : Integer @primaryKey(MySQL primary key);
	name : String;
	age : int;
end

rule "Test Metadata"
	when
		$p : Person(age > 30);
	then
		System.out.println("大于30岁的人：" + $p.getName());
		droolsResultDTO.setRetStatus(true);
        droolsResultDTO.setRemark("大于30岁的人：" + $p.getName());
        droolsResultDTO.setRuleScore(75f);
end